-------------------------------------------------------------------------------
Test set: DPcalcTests
-------------------------------------------------------------------------------
Tests run: 26, Failures: 3, Errors: 6, Skipped: 0, Time elapsed: 0.316 sec <<< FAILURE! - in DPcalcTests
testGetAssignmentWhereSubjectIsInCapitalLetters(DPcalcTests)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.UnsupportedOperationException: You still need to complete this method
	at za.ac.pearson.cti.studentdpcalculator.DPcalc.getAssignmentMark(DPcalc.java:170)
	at DPcalcTests.testGetAssignmentWhereSubjectIsInCapitalLetters(DPcalcTests.java:406)

testGetAssignmentWithSubjectThatDoesNotExist(DPcalcTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.ArrayIndexOutOfBoundsException> but was<java.lang.UnsupportedOperationException>
	at za.ac.pearson.cti.studentdpcalculator.DPcalc.getAssignmentMark(DPcalc.java:170)
	at DPcalcTests.testGetAssignmentWithSubjectThatDoesNotExist(DPcalcTests.java:393)

testGetAssignmentMarkWithMultipleSubjects(DPcalcTests)  Time elapsed: 0.087 sec  <<< ERROR!
java.lang.UnsupportedOperationException: Not supported yet.
	at za.ac.pearson.cti.studentdpcalculator.DPcalc.addSubject(DPcalc.java:234)
	at DPcalcTests.testGetAssignmentMarkWithMultipleSubjects(DPcalcTests.java:440)

testGetSemesterTestMarkWithMultipleSubjects(DPcalcTests)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsupportedOperationException: Not supported yet.
	at za.ac.pearson.cti.studentdpcalculator.DPcalc.addSubject(DPcalc.java:234)
	at DPcalcTests.testGetSemesterTestMarkWithMultipleSubjects(DPcalcTests.java:506)

testValidDVnum(DPcalcTests)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at DPcalcTests.testValidDVnum(DPcalcTests.java:192)

testGetSemesterTestWithSubjectThatDoesNotExist(DPcalcTests)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: java.lang.ArrayIndexOutOfBoundsException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testGetAssignmentWhereSubjectIsOnlyInLowerCase(DPcalcTests)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsupportedOperationException: You still need to complete this method
	at za.ac.pearson.cti.studentdpcalculator.DPcalc.getAssignmentMark(DPcalc.java:170)
	at DPcalcTests.testGetAssignmentWhereSubjectIsOnlyInLowerCase(DPcalcTests.java:421)

testGetContinuousAssessmentWithSubjectThatDoesNotExist(DPcalcTests)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: java.lang.ArrayIndexOutOfBoundsException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testGetContinuousAssessmentWithMultipleSubjects(DPcalcTests)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsupportedOperationException: Not supported yet.
	at za.ac.pearson.cti.studentdpcalculator.DPcalc.addSubject(DPcalc.java:234)
	at DPcalcTests.testGetContinuousAssessmentWithMultipleSubjects(DPcalcTests.java:572)

